name: flutterapp
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.2
  firebase_auth: ^5.4.1
  animated_bottom_navigation_bar: ^1.3.3
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.4
  crypto: ^3.0.1
  font_awesome_flutter: ^10.1.0
  google_fonts: ^6.0.1
  # provider: 6.0.3
  # rxdart: 0.27.4
  # json_annotation: 4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # build_runner: 2.1.11
  # json_serializable: 6.2.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - assets/
  #   - assets/covers/
  #   - assets/congrats.gif